config/routes.rb
SpecialOlympicsApplication::Application.routes.draw do

  resources :teachers

  resources :groups

  get "heat_sheet_generator/index"
  get '/index/heat_sheet_generator', to: 'heat_sheet_generator#index'
  get '/index/heats', to: 'heats#index'
  get '/index/athletes', to: 'athletes#index'
  get '/index/events', to: 'events#index'
  get '/index/groups', to: 'groups#index'

  resources :heat_sheet_generator do
    member {get "download"}
  end

  get '/heatsheets/download', to: 'heat_sheet_generator#download'

  resources :teachers do
    collection {post :import}
  end

  resources :groups do
    collection { post :import }
  end

  resources :athletes do
    collection { post :import }
  end
  
  resources :heats do 
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  root 'welcome#index'

  

end

app/models/heat.rb
class Heat < ActiveRecord::Base
  attr_accessible :event_id, :gender, :min_age, :max_age, :time, :num_heats
  belongs_to :event
  has_and_belongs_to_many :athletes
  # Validations
  validates_associated :event
  validates :gender, inclusion:{in: %w(M F B)}
  validates :min_age, numericality:{only_integer: true, greater_than: 0}
  validates :max_age, numericality:{only_integer: true, greater_than_or_equal_to: :min_age}
  validates :time, format:{with: /\A[0-2]?[0-9]:[0-5][0-9]:00+\z/, message: "Format: hours:minutes:seconds, where 0<=hours<=24, 0<=minutes<=59, seconds=00, e.g. 11:30:00"}
  validates :num_heats, numericality:{only_integer: true, greater_than: 0}

  # Takes file and parses it
  def self.import(file)
		spreadsheet = open_spreadsheet(file)

		(2..spreadsheet.last_row).each do |i|

			# create new heat
			heat = Heat.create
			# find event associated with heat
			event = Event.find_by_event_code(spreadsheet.row(i)[0])

			# set attributes of heat
			heat.event_id = event.id
			heat.gender = spreadsheet.row(i)[2]
			heat.min_age = spreadsheet.row(i)[3]
			heat.max_age = spreadsheet.row(i)[4]
			heat.time = spreadsheet.row(i)[5]
			heat.num_heats = spreadsheet.row(i)[6]

			# save heat
			heat.save
			# sets up belongs_to association with event
			event.heats.concat(heat)
			# save event
			event.save
		end
	end

	# Opens a file using the roo gem
	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Roo::Csv.new(file.path)
		else raise "Unkown file type: #{file.original_filename}"
		end
	end
end

app/controllers/heats_controller.rb
class HeatsController < ApplicationController
  before_action :set_heat, only: [:show, :edit, :update, :destroy]

  # GET /heats
  # GET /heats.json
  def index
    @heats = Heat.all
  end

  # GET /heats/1
  # GET /heats/1.json
  def show
  end

  # GET /heats/new
  def new
    @heat = Heat.new
  end

  # GET /heats/1/edit
  def edit
  end

  # POST /heats
  # POST /heats.json
  def create
    @heat = Heat.new(heat_params)

    respond_to do |format|
      if @heat.save
        format.html { redirect_to @heat, notice: 'Heat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @heat }
      else
        format.html { render action: 'new' }
        format.json { render json: @heat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heats/1
  # PATCH/PUT /heats/1.json
  def update
    respond_to do |format|
      if @heat.update(heat_params)
        format.html { redirect_to @heat, notice: 'Heat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @heat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heats/1
  # DELETE /heats/1.json
  def destroy
    @heat.destroy
    respond_to do |format|
      format.html { redirect_to heats_url }
      format.json { head :no_content }
    end
  end


  # Imports a file to pass to heat model
  def import
    Heat.import(params[:file])
    redirect_to heats_path, notice: "Heats imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heat
      @heat = Heat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heat_params
      params.require(:heat).permit(:event_id, :gender, :min_age, :max_age, :time, :num_heats)
    end
end

app/helpers/heats_helper.rb
module HeatsHelper
end

app/views/heats/_form.html.erb
<%= form_for(@heat) do |f| %>
  <% if @heat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@heat.errors.count, "error") %> prohibited this heat from being saved:</h2>

      <ul>
      <% @heat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :min_age %><br>
    <%= f.text_field :min_age %>
  </div>
  <div class="field">
    <%= f.label :max_age %><br>
    <%= f.text_field :max_age %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :num_heats %><br>
    <%= f.text_field :num_heats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heats/edit.html.erb
<h1>Edit Heat</h1>


<%= form_for :heat, url: heat_path(@heat), method: :patch do |heat| %>
  <!-- Check for and display errors -->
  <% if @heat.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@heat.errors.count, "error") %> prevented
      this heat from being edited:</h2>
    <ul>
    <% @heat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <!-- Value fields -->
  <p>
    <strong>Event Name:</strong><br>
    <%= Event.find_by_id(@heat.event_id).event_name %>
  </p>

  <p>
    <strong>Gender:</strong><br>
    <div class="field">
      <%= heat.label :gender, "M", :value => "M" %>
      <%= heat.radio_button :gender, "M" %>
      <%= heat.label :gender, "F", :value => "F" %>
      <%= heat.radio_button :gender, "F" %>
      <%= heat.label :gender, "B", :value => "B" %>
      <%= heat.radio_button :gender, "B" %>
    </div>
  </p>

  <p>
    <strong>Min age:</strong><br>
    <%= heat.text_field :min_age %>
  </p>

  <p>
    <strong>Max age:</strong><br>
    <%= heat.text_field :max_age %>
  </p>

  <p>
    <strong>Time:</strong><br>
    <%= heat.text_field :time %>
  </p>

  <p>
    <strong>Num heats:</strong><br>
    <%= heat.text_field :num_heats %>
  </p>
  <!-- Save edits -->
  <p>
    <%= heat.submit %>
  </p>
<% end %>

<!-- Navigation links -->
<%= link_to 'Show', @heat %> |
<%= link_to 'Back', heats_path %>

app/views/heats/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <!-- Header info -->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Heats</title>
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

  </head>

<p id="notice"><%= notice %></p>
  <body> 

    <div class="container-fluid">
      <div class="row">


          <h1 class="page-header">Heats</h1>
          <!-- Add heat button -->
	  <%= button_to 'Add Heat', new_heat_path, method: :get%>

          <!-- Heats table -->
	  <div class="table-responsive">
	    <table class="table table-striped">
  	      <thead>
    	        <tr>
                  <th>Heat ID</th>
                  <th>Gender</th>
                  <th>Min age</th>
                  <th>Max age</th>
      	 	  <th>Time</th>
      		  <th>Num heats</th>
      		  <th></th>
    		</tr>
  	      </thead>

  	      <tbody>
              <% @heats.each do |heat| %>
                <tr>
        	  <td><%= heat.id %>
        	  <td><%= heat.gender %></td>
        	  <td><%= heat.min_age %></td>
        	  <td><%= heat.max_age %></td>
        	  <td><%= heat.time %></td>
        	  <td><%= heat.num_heats %></td>
                  <!-- Edit and delete buttons -->
        	  <td><div class="btn-group">  
		   <button class="btn">Action</button>
		   <button class="btn dropdown-toggle" data-toggle="dropdown">
		     <span class="caret"></span>
		   </button>
		   <u1 class="dropdown-menu">      	
        	     <li><%= button_to 'Edit', edit_heat_path(heat), method: :get%></li>
        	     <li><%= button_to 'Delete', heat, data: { confirm: 'Are you sure?' }, method: :delete%></li></u1></div></td>
      		</tr>
    	      <% end %>
  	      </tbody>
	    </table>
	  </div>
        </div>
      </div>

      <!-- File import options
      <br>
      <strong>Import using heats.csv file.</strong>
      <%= form_tag import_heats_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import" %>
      <% end %>
    -->
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
  </body>
</html>

app/views/heats/new.html.erb
<h1>New Heat</h1>

<%= form_for :heat, url: heat_path(@heat) do |heat| %>
  <!-- Check for and display errors -->
  <% if @heat.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@heat.errors.count, "error") %> prevented
      this heat from being created:</h2>
    <ul>
    <% @heat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <!-- Value fields -->
  <p>
    <strong>Event ID:</strong><br>
    <%= heat.text_field :event_id %>	
  </p>

  <p>
    <strong>Gender:</strong><br>
    <div class="field">
      <%= heat.label :gender, "M", :value => "M" %>
      <%= heat.radio_button :gender, "M" %>
      <%= heat.label :gender, "F", :value => "F" %>
      <%= heat.radio_button :gender, "F" %>
      <%= heat.label :gender, "B", :value => "B" %>
      <%= heat.radio_button :gender, "B" %>
    </div>
  </p>

  <p>
    <strong>Min age:</strong><br>
    <%= heat.text_field :min_age %>
  </p>

  <p>
    <strong>Max age:</strong><br>
    <%= heat.text_field :max_age %>
  </p>

  <p>
    <strong>Time:</strong><br>
    <%= heat.text_field :time %>
  </p>

  <p>
    <strong>Num heats:</strong><br>
    <%= heat.text_field :num_heats %>
  </p>

  <!-- Save new heat -->
  <p>
    <%= heat.submit %>
  </p>
<% end %>

<!-- Navigation links -->
<%= link_to 'Back', heats_path %>

app/views/heats/show.html.erb
<p id="notice"><%= notice %></p>
<!-- Value fields -->
<p>
  <strong>Event Name:</strong>
  <%= Event.find_by_id(@heat.event_id).event_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @heat.gender %>
</p>

<p>
  <strong>Min age:</strong>
  <%= @heat.min_age %>
</p>

<p>
  <strong>Max age:</strong>
  <%= @heat.max_age %>
</p>

<p>
  <strong>Time:</strong>
  <%= @heat.time %>
</p>

<p>
  <strong>Num heats:</strong>
  <%= @heat.num_heats %>
</p>

<!-- Navigation links -->
<%= link_to 'Edit', edit_heat_path(@heat) %> |
<%= link_to 'Back', heats_path %>