config/routes.rb
SpecialOlympicsApplication::Application.routes.draw do

  resources :teachers

  resources :groups

  get "heat_sheet_generator/index"
  get '/index/heat_sheet_generator', to: 'heat_sheet_generator#index'
  get '/index/heats', to: 'heats#index'
  get '/index/athletes', to: 'athletes#index'
  get '/index/events', to: 'events#index'
  get '/index/groups', to: 'groups#index'

  resources :heat_sheet_generator do
    member {get "download"}
  end

  get '/heatsheets/download', to: 'heat_sheet_generator#download'

  resources :teachers do
    collection {post :import}
  end

  resources :groups do
    collection { post :import }
  end

  resources :athletes do
    collection { post :import }
  end
  
  resources :heats do 
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  root 'welcome#index'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	attr_accessible :group_code, :school_name
	has_many :teachers

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		(2..spreadsheet.last_row).each do |i|

			# check if group is already in the database
			group = Group.find_by_group_code(spreadsheet.row(i)[0])
			
			# if group does not exist
			if group == nil 
				group = Group.create

				# set the attributes of Group
				group.group_code = spreadsheet.row(i)[0]
				group.school_name = spreadsheet.row(i)[1]

				group.save
			end
		end
	end

	# Opens a file using the roo gem
	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Roo::Csv.new(file.path)
		else raise "Unkown file type: #{file.original_filename}"
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def import
  Group.import(params[:file])
    redirect_to groups_path, notice: "Groups imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_code, :school_name, :group_leader)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_code %><br>
    <%= f.text_field :group_code %>
  </div>
  <div class="field">
    <%= f.label :school_name %><br>
    <%= f.text_field :school_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Group code</th>
      <th>School name</th>
      <th>Group leader</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_code %></td>
        <td><%= group.school_name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--
<strong>Import using athletes.csv file</strong>
<%= form_tag import_groups_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
-->

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group code:</strong>
  <%= @group.group_code %>
</p>

<p>
  <strong>School name:</strong>
  <%= @group.school_name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>