config/routes.rb
SpecialOlympicsApplication::Application.routes.draw do

  resources :teachers

  resources :groups

  get "heat_sheet_generator/index"
  get '/index/heat_sheet_generator', to: 'heat_sheet_generator#index'
  get '/index/heats', to: 'heats#index'
  get '/index/athletes', to: 'athletes#index'
  get '/index/events', to: 'events#index'
  get '/index/groups', to: 'groups#index'

  resources :heat_sheet_generator do
    member {get "download"}
  end

  get '/heatsheets/download', to: 'heat_sheet_generator#download'

  resources :teachers do
    collection {post :import}
  end

  resources :groups do
    collection { post :import }
  end

  resources :athletes do
    collection { post :import }
  end
  
  resources :heats do 
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  root 'welcome#index'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
	attr_accessible :event_code, :event_name, :score_unit, :min_score, :max_score, :sort_seq
	has_many :heats, :dependent => :destroy
        # validations
        validates :event_code, format: { with: /\E[0-9][0-9][0-9]\z/, message: "Format: E followed by 3 digit code, e.g. E001"}
        validates :event_name, length:{in: 1..50}
	validates :score_unit, inclusion:{in: %w(T D N)}
	validates :min_score, numericality:{greater_than_or_equal_to: 0, message: "Should be a positive integer value"}
	validates :max_score, numericality:{greater_than_or_equal_to: :min_score, message: "Should be an integer greater than min score"}
	validates :sort_seq, numericality:{ only_integer: true, message: "Should be an integer value"}
      
	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = ["event_code","event_name","score_unit","min_score","max_score","sort_seq"]
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]

			event = find_by_event_code(row["event_code"]) || new
			event.attributes = row.to_hash.slice(*accessible_attributes)
			event.save!
		end
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Roo::Csv.new(file.path)
		else raise "Unkown file type: #{file.original_filename}"
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]


  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def import
    Event.import(params[:file])
    redirect_to events_path, notice: "Events imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_code, :event_name, :score_unit, :min_score, :max_score, :sort_seq)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_code %><br>
    <%= f.text_field :event_code %>
  </div>
  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :score_unit %><br>
    <%= f.text_field :score_unit %>
  </div>
  <div class="field">
    <%= f.label :min_score %><br>
    <%= f.number_field :min_score %>
  </div>
  <div class="field">
    <%= f.label :max_score %><br>
    <%= f.number_field :max_score %>
  </div>
  <div class="field">
    <%= f.label :sort_seq %><br>
    <%= f.number_field :sort_seq %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>


  
<%= form_for :event, url: event_path(@event), method: :patch do |event| %>
  <!-- Check for and display errors --> 
  <% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prevented
      this event from being edited:</h2>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <!-- Value fields -->
  <p>
    <strong>Event Code:</strong><br>
    <%= event.text_field :event_code%>
  </p>

  <p>
    <strong>Event Name:</strong><br>
    <%= event.text_field :event_name%>
  </p>

  <p>
    <strong>Score Unit:</strong><br>
    <div class="field">
      <%= event.label :score_unit, "T", :value => "T" %>
      <%= event.radio_button :score_unit, "T" %>
      <%= event.label :score_unit, "D", :value => "D" %>
      <%= event.radio_button :score_unit, "D" %>
      <%= event.label :score_unit, "N", :value => "N" %>
      <%= event.radio_button :score_unit, "N" %>
    </div>
  </p>

  <p>
    <strong>Min Score:</strong><br>
    <%= event.text_field :min_score%>
  </p>

  <p>
    <strong>Max Score:</strong><br>
    <%= event.text_field :max_score%>
  </p>

  <p>
    <strong>Sort Seq:</strong><br>
    <%= event.text_field :sort_seq%>
  </p>
  <!-- Save edits -->
  <p>
    <%= event.submit %>
  </p>
<% end %>
 
<!-- Navigation links -->
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">

<!-- Header info -->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Events</title>
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

  </head>

<p id="notice"><%= notice %></p>
  <body> 

    <div class="container-fluid">
      <div class="row">


          <h1 class="page-header">Events</h1>
          <!-- Add event button -->
	  <%= button_to 'Add Event', new_event_path, method: :get%>  

          <!-- Events table -->
          <div class="table-responsive">
            <table class="table table-striped">
  	      <thead>
                <tr>
      		    <th>Event ID</th>
      		    <th>Event Code</th>
      		    <th>Event Name</th>
     		    <th>Score Unit</th>
      		    <th>Min Score</th>
      		    <th>Max Score</th>
      		    <th>Sort Seq</th>
      		    <th></th>
    	        </tr>
 	      </thead>
             <tbody>
             <% @events.each do |event| %>
               <tr>
                 <td><%= event.id %></td>
       		 <td><%= event.event_code %></td>
       		 <td><%= event.event_name %></td>
     	   	 <td><%= event.score_unit %></td>
        	 <td><%= event.min_score %></td>
       		 <td><%= event.max_score %></td>
      		 <td><%= event.sort_seq %></td>
                 <!-- Edit and delete buttons -->
		 <td><div class="btn-group">  
		   <button class="btn">Action</button>
		   <button class="btn dropdown-toggle" data-toggle="dropdown">
		     <span class="caret"></span>
		   </button>
		   <u1 class="dropdown-menu">      	
        	     <li><%= button_to 'Edit', edit_event_path(event), method: :get%></li>
        	     <li><%= button_to 'Delete', event, data: { confirm: 'Are you sure?' }, method: :delete%></li></u1></div></td>
      	       </tr>
             <% end %>
           </tbody>
            
            </table>
          </div>
        </div>
      </div>

      <!-- File import options 
      <br>
      <strong>Import using events.csv file</strong>
      <%= form_tag import_events_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import" %>
      <% end %>
      -->
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/docs.min.js"></script>
  </body>
</html>

app/views/events/new.html.erb
<h1>New event</h1>

<%= form_for :event, url: event_path(@event) do |event| %>
  <!-- Check for and display errors -->
  <% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prevented
      this event from being created:</h2>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <!-- Value fields -->
  <p>
    <strong>Event Code:</strong><br>
    <%= event.text_field :event_code%>
  </p>

  <p>
    <strong>Event Name:</strong><br>
    <%= event.text_field :event_name%>
  </p>

  <p>
    <strong>Score Unit:</strong><br>
    <div class="field">
      <%= event.label :score_unit, "T", :value => "T" %>
      <%= event.radio_button :score_unit, "T" %>
      <%= event.label :score_unit, "D", :value => "D" %>
      <%= event.radio_button :score_unit, "D" %>
      <%= event.label :score_unit, "N", :value => "N" %>
      <%= event.radio_button :score_unit, "N" %>
    </div>
  </p>

  <p>
    <strong>Min Score:</strong><br>
    <%= event.text_field :min_score%>
  </p>

  <p>
    <strong>Max Score:</strong><br>
    <%= event.text_field :max_score%>
  </p>

  <p>
    <strong>Sort Seq:</strong><br>
    <%= event.text_field :sort_seq%>
  </p>
  <!-- Save entry -->
  <p>
    <%= event.submit %>
  </p>
<% end %>

<!-- Navigation links -->
<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<!-- Value fields -->
<p>
  <strong>Event Code:</strong>
  <%= @event.event_code %>
</p>

<p>
  <strong>Event Name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Score Unit:</strong>
  <%= @event.score_unit %>
</p>

<p>
  <strong>Min Score:</strong>
  <%= @event.min_score %>
</p>

<p>
  <strong>Max Score:</strong>
  <%= @event.max_score %>
</p>

<p>
  <strong>Sort Seq:</strong>
  <%= @event.sort_seq %>
</p>

<!-- Navigation links -->
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>