config/routes.rb
SpecialOlympicsApplication::Application.routes.draw do

  resources :teachers

  resources :groups

  get "heat_sheet_generator/index"
  get '/index/heat_sheet_generator', to: 'heat_sheet_generator#index'
  get '/index/heats', to: 'heats#index'
  get '/index/athletes', to: 'athletes#index'
  get '/index/events', to: 'events#index'
  get '/index/groups', to: 'groups#index'

  resources :heat_sheet_generator do
    member {get "download"}
  end

  get '/heatsheets/download', to: 'heat_sheet_generator#download'

  resources :teachers do
    collection {post :import}
  end

  resources :groups do
    collection { post :import }
  end

  resources :athletes do
    collection { post :import }
  end
  
  resources :heats do 
    collection { post :import }
  end

  resources :events do
    collection { post :import }
  end

  root 'welcome#index'

  

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :group

  	def self.import(file)
  		spreadsheet = open_spreadsheet(file)
		(2..spreadsheet.last_row).each do |i|
			
			# check if teacher is already in the database
			# group = Group.find_by_group_code(spreadsheet.row(i)[0])
			teacher = Teacher.find_by_name(spreadsheet.row(i)[2])


			if teacher == nil
				teacher = Teacher.create

				# set the attributes of Teacher
				teacher.name = spreadsheet.row(i)[2]
				teacher.group_id = Group.find_by_group_code(spreadsheet.row(i)[0]).id

				teacher.save
			end
		end
	end


		# Opens a file using the roo gem
	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Roo::Csv.new(file.path)
		else raise "Unkown file type: #{file.original_filename}"
		end
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  def import
  Teacher.import(params[:file])
    redirect_to teachers_path, notice: "Teachers imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :group_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.group %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<strong>Import using heats.csv file.</strong>
<%= form_tag import_teachers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @teacher.group %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>